=== Organ-CrazyBugs/mszhan-redwine-manage-server/src/main/resources/com/mszhan/redwine/manage/server/core/excelContent/excelContentSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="contents">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="content"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="content">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="headerTitle"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:string"/>
            <xs:attribute name="fileName" use="required" type="xs:string"/>
            <xs:attribute name="complex" use="optional" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="headerTitle">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="itemTitle"/>
            </xs:sequence>
            <xs:attribute name="color" use="optional" >
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="WHITE"/>
                        <xs:enumeration value="BLUE"/>
                        <xs:enumeration value="YELLOW"/>
                        <xs:enumeration value="GREEN"/>
                        <xs:enumeration value="BLACK"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="comment" use="optional" type="xs:string"/>
            <xs:attribute name="font-color" use="optional"  >
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="WHITE"/>
                        <xs:enumeration value="BLUE"/>
                        <xs:enumeration value="YELLOW"/>
                        <xs:enumeration value="GREEN"/>
                        <xs:enumeration value="BLACK"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="font-size" use="optional" type="xs:integer"/>
            <xs:attribute name="item-color" use="optional"  >
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="WHITE"/>
                        <xs:enumeration value="BLUE"/>
                        <xs:enumeration value="YELLOW"/>
                        <xs:enumeration value="GREEN"/>
                        <xs:enumeration value="BLACK"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="item-font-color" use="optional" >
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="WHITE"/>
                        <xs:enumeration value="BLUE"/>
                        <xs:enumeration value="YELLOW"/>
                        <xs:enumeration value="GREEN"/>
                        <xs:enumeration value="BLACK"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="item-font-size" use="optional" type="xs:integer"/>
            <xs:attribute name="key" use="optional" type="xs:string"/>
            <xs:attribute name="length" use="optional" type="xs:integer"/>
            <xs:attribute name="necessary" use="optional" type="xs:boolean"/>
            <xs:attribute name="text" use="required" type="xs:string"/>
            <!--<xs:attribute name="type" use="optional" type="xs:string"/>-->
            <xs:attribute name="type" use="optional"  >
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="String"/>
                        <xs:enumeration value="BigDecimal"/>
                        <xs:enumeration value="Date"/>
                        <xs:enumeration value="Integer"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>

            <xs:attribute name="format" use="optional" type="xs:string"/>
            <!--<xs:attribute name="select" use="optional" type="xs:string"/>-->
            <xs:attribute name="select" use="optional" >
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="text"/>
                        <xs:enumeration value="boolean"/>
                        <!--<xs:enumeration value="BLUE"/>-->
                        <!--<xs:enumeration value="YELLOW"/>-->
                        <!--<xs:enumeration value="GREEN"/>-->
                        <!--<xs:enumeration value="BLACK"/>-->
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="itemTitle">
        <xs:complexType>
            <xs:attribute name="color" use="optional" >
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="WHITE"/>
                        <xs:enumeration value="BLUE"/>
                        <xs:enumeration value="YELLOW"/>
                        <xs:enumeration value="GREEN"/>
                        <xs:enumeration value="BLACK"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="comment" use="optional" type="xs:string"/>
            <xs:attribute name="font-color" use="optional"  >
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="WHITE"/>
                        <xs:enumeration value="BLUE"/>
                        <xs:enumeration value="YELLOW"/>
                        <xs:enumeration value="GREEN"/>
                        <xs:enumeration value="BLACK"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="font-size" use="optional" type="xs:integer"/>
            <xs:attribute name="item-color" use="optional"  >
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="WHITE"/>
                        <xs:enumeration value="BLUE"/>
                        <xs:enumeration value="YELLOW"/>
                        <xs:enumeration value="GREEN"/>
                        <xs:enumeration value="BLACK"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="item-font-color" use="optional" >
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="WHITE"/>
                        <xs:enumeration value="BLUE"/>
                        <xs:enumeration value="YELLOW"/>
                        <xs:enumeration value="GREEN"/>
                        <xs:enumeration value="BLACK"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="item-font-size" use="optional" type="xs:integer"/>
            <xs:attribute name="key" use="required" type="xs:string"/>
            <xs:attribute name="length" use="optional" type="xs:integer"/>
            <xs:attribute name="necessary" use="optional" type="xs:boolean"/>
            <xs:attribute name="text" use="required" type="xs:string"/>
            <!--<xs:attribute name="type" use="required" type="xs:string"/>-->
            <xs:attribute name="type" use="required"  >
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="String"/>
                        <xs:enumeration value="BigDecimal"/>
                        <xs:enumeration value="Date"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="format" use="optional" type="xs:string"/>
            <xs:attribute name="select" use="optional" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Organ-CrazyBugs/mszhan-redwine-manage-server/src/main/resources/com/mszhan/redwine/manage/server/core/excelContent/content.xml
<?xml version="1.0" encoding="UTF-8"?>

<contents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="excelContentSchema.xsd" >
    <content name="fbaAgeInventoryPriceImport" fileName="价格维护导入模板 " >
        <headerTitle text="期间"  type="String"  key = "periodDate"   font-size="9" necessary="true"  color="BLUE"   item-font-size="9" font-color="WHITE" item-font-color="BLACK" length="12"   item-color="YELLOW"   ></headerTitle>
        <headerTitle text="小组" type="String"  key = "groupName"  font-size="9" necessary="true"  color="BLUE" item-font-color="BLACK" font-color="WHITE"  item-font-size="9" length="12"   item-color="YELLOW"   ></headerTitle>
        <headerTitle text="亚马逊SKU" type="String"  key = "amazonSku"  font-size="9" necessary="true"  color="BLUE"  item-font-size="9" font-color="WHITE"  length="12" item-font-color="BLACK"   item-color="YELLOW"   />
        <headerTitle text="FNSKU" type="String"  key = "fnsku"  font-size="9" necessary="true"  color="BLUE"  item-font-size="9" font-color="WHITE"  length="12" item-font-color="BLACK"   item-color="YELLOW"   />
        <headerTitle text="单价" type="BigDecimal"  key = "unitPrice"  font-size="9" necessary="true"  color="BLUE"  item-font-size="9" font-color="WHITE"  length="12" item-font-color="BLACK"   item-color="YELLOW"   />
    </content>

    <content name="outboundDetail" fileName="出库导出" >
        <headerTitle text="仓库" type="String"  key = "warehouseName"  font-size="9" necessary="true"  color="BLUE"  item-font-size="9" font-color="WHITE"  length="12" item-font-color="BLACK"   item-color="YELLOW"   />
        <headerTitle text="出库类型"  type="String"  key = "type"   font-size="9" necessary="true"  color="BLUE"   item-font-size="9" font-color="WHITE" item-font-color="BLACK" length="12"   item-color="YELLOW"   />
        <headerTitle text="产品名称" type="String"  key = "productName"  font-size="9" necessary="true"  color="BLUE" item-font-color="BLACK" font-color="WHITE"  item-font-size="9" length="12"   item-color="YELLOW"   />
        <headerTitle text="条码" type="String"  key = "sku"  font-size="9" necessary="true"  color="BLUE"  item-font-size="9" font-color="WHITE"  length="12" item-font-color="BLACK"   item-color="YELLOW"   />
        <headerTitle text="数量" type="Integer"  key = "quantity"  font-size="9" necessary="true"  color="BLUE"  item-font-size="9" font-color="WHITE"  length="12" item-font-color="BLACK"   item-color="YELLOW"   />
        <headerTitle text="单价" type="String"  key = "unitPrice"  font-size="9" necessary="true"  color="BLUE"  item-font-size="9" font-color="WHITE"  length="12" item-font-color="BLACK"   item-color="YELLOW"   />
        <headerTitle text="操作时间" type="String"  key = "createDate"  font-size="9" necessary="true"  color="BLUE"  item-font-size="9" font-color="WHITE"  length="12" item-font-color="BLACK"   item-color="YELLOW"   />
        <headerTitle text="操作人" type="String"  key = "creatorName"  font-size="9" necessary="true"  color="BLUE"  item-font-size="9" font-color="WHITE"  length="12" item-font-color="BLACK"   item-color="YELLOW"   />
    </content>


</contents>
